@startuml "Pages"
object Connexion
object Inscription
object HUB
object Messagerie
object RechercheOffres
object DepotOffres
object ListeOffres
object Offre
object Reservation
object HEADER
object FOOTER
object Profil
object MesOffres
object MonPlanning
object Admin
object Reclamation

Connexion -> Inscription : ""
Connexion -down-> HUB : "Connexion réussie"
Inscription -> Connexion : "Inscription réussie"
HUB -down-> RechercheOffres : ""
HEADER -> DepotOffres : ""
HEADER -down-> Messagerie : ""
HEADER -down-> Profil : ""
HEADER -> Connexion : "Déconnexion"
Profil -down-> MesOffres : ""
Profil -down-> MonPlanning : ""
HUB -down-> DepotOffres : ""
RechercheOffres -down-> ListeOffres : "Recherche effectuée"
ListeOffres -down-> Offre : "Choix d'une offre"
Offre -down-> Reservation : ""
DepotOffres -down-> Offre : "Dépôt réalisé"
FOOTER -down-> Reclamation : ""
FOOTER -down-> Admin : ""

HEADER : Absent avant connexion
FOOTER : Absent avant connexion
MesOffres : ListeOffres avec filtre
HUB : + Notifications
FOOTER : + Crédits
Offre : + Détails
Offre : + Long. liste d'attente
Offre : + Planning
@enduml